### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by luisalrp** [gmickel/turborepo-shadcn-nextjs#1]
Hey Gordon,

Thanks for creating this template. I'm trying to install on it [Storybook](https://storybook.js.org/) but I'm not being successful. Would you mind to include it?

Thanks!

**Comment by gmickel** [comment]
Hi there!

Definitely something I could look at. What issues did you run into?

**Comment by gmickel** [comment]
Storybook is now included, have fun! 🚀
